---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: curlyos
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - from-file: subrecipes/packages.yml
  - from-file: subrecipes/flatpak.yml

  - type: files
    files:
      - source: system
        destination: /

  - type: systemd
    system:
      enabled:
        - sddm.service

  - type: os-release
    properties:
      ID: curlyos
      ID_LIKE: fedora
      NAME: CurlyOS
      PRETTY_NAME: CurlyOS
      DEFAULT_HOSTNAME: curlyos

  - type: signing
