---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: leux-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - from-file: subrecipes/packages.yml
  - from-file: subrecipes/flatpak.yml

  - type: files
    files:
      - source: system
        destination: /

  - type: systemd
    system:
      enabled:
        - greetd.service

  - type: signing
